### ISSUE TITLE
FCN qualitative results

### ISSUE THREAD

**Issue by aravindhm** [xiaolonw/ss-gan#1]
Running `th test_fcn.lua` on sample images from the dataset resulted in poor qualitative results. I have attached a prediction and corresponding ground truth image. This is using the trained FCN model downloaded from the dropbox link provided in the README.md

![2](https://cloud.githubusercontent.com/assets/2454281/19648696/da450bc6-99fa-11e6-93ff-4f7477ab3962.jpg)

![00000001_label](https://cloud.githubusercontent.com/assets/2454281/19648569/60fb7840-99fa-11e6-9c4b-8373adc28e96.jpg)

![0002](https://cloud.githubusercontent.com/assets/2454281/19648798/3e58af96-99fb-11e6-8699-4beccec2b965.jpg)

![4](https://cloud.githubusercontent.com/assets/2454281/19648744/1155a076-99fb-11e6-9d70-19007318b2cb.jpg)

![00000001_label](https://cloud.githubusercontent.com/assets/2454281/19648751/1912c2b2-99fb-11e6-8d78-01dc87b87eac.jpg)

![0004](https://cloud.githubusercontent.com/assets/2454281/19648805/42cb009c-99fb-11e6-928f-58e05bf888a5.jpg)

Are these qualitative results as expected? ... surface normal prediction is a hard problem!

I have changed `list_file` and `path_dataset` variables to point to my images but everything else is the same.

**Comment by xiaolonw** [comment]
are you sure the prediction result is corresponding to the right image? Since the output of FCN is in low resolution (32 \* 32), it might not get the details right, but the it should get the whole layout right.

**Comment by aravindhm** [comment]
Hi @xiaolonw  It must have been an error in how I used it because the results seem fine in another experiment. Thanks!
